Write-in select option support
parameter1/identity-x pull request #13
Opened 2022-04-28 19:56 UTC by solocommand

Adds support for write-in values on custom select options.
Also resolves bug where a selected value couldn't be unset.

## Field definition
<img width="857" alt="image" src="https://user-images.githubusercontent.com/1778222/165834116-4681b087-8f4e-451b-bd9d-cf488dbd78ad.png">

```graphql
mutation UpdateSelectField($input: UpdateSelectFieldMutationInput!) {
  updateSelectField(input: {
    id: "618ab74dcd3e2f0147386c42",
    name: "Game preference",
    label: "What is your favorite game?",
    externalId: {
      identifier: { type: "thud", value: "qux" },
      namespace: { provider: "foo", tenant: "bar", type: "baz" }
    },
    options: [
      {
        id: "618ab74dcd3e2f0147386c43",
        label: "Scrabble",
        externalIdentifier: "foo-bar",
        canWriteIn: false
      },
      {
        id: "626ab183cd3af80041f3cbc7",
        label: "Other",
        externalIdentifier: "foo-other",
        canWriteIn: true
      }
    ]
  }) {
    id
    type
    name
    label
    required
    active
    options {
      id
      label
      externalIdentifier
      canWriteIn
    }
    externalId {
      id
       identifier {
        type
        value
      }
      namespace {
        provider
        tenant
        type
      }
    }
    createdAt
    updatedAt
  }
}
```

## User answers
<img width="838" alt="image" src="https://user-images.githubusercontent.com/1778222/165840135-901cd9a0-1714-4f14-bf34-d4d94e375582.png">

<img width="821" alt="image" src="https://user-images.githubusercontent.com/1778222/165834055-9d53a786-9e0f-4c7d-9097-a7f7c1f2efdc.png">

<img width="821" alt="image" src="https://user-images.githubusercontent.com/1778222/165834001-af66378b-15cb-4970-9a20-9afa8c32548f.png">

```graphql
mutation UpdateAppUserCustomSelectAnswers($input: UpdateAppUserCustomSelectAnswersMutationInput!) {
  updateAppUserCustomSelectAnswers(input: {
    id: "some-user-id",
    answers: [
      {
        fieldId: "618ab74dcd3e2f0147386c42",
        optionIds: ["626ab183cd3af80041f3cbc7"],
        writeInValues: [
          {
            optionId: "626ab183cd3af80041f3cbc7",
            value: "foo-bar-baz-qux-quzbot"
          }
        ]
      }
    ]
  }) {
    id
    email
    domain
    name
    customSelectFieldAnswers(input: { onlyActive: true }) {
      id
      field {
        id
        name
        label
      }
      answers {
        id
        label
        writeInValue
      }
    }
  }
}
```

2022-04-28 19:56 UTC, solocommand commented
![](https://github.trello.services/images/mini-trello-icon.png) [Write-in support for select fields](https://trello.com/c/upRaKFsC/2-write-in-support-for-select-fields)

2022-04-28 21:15 UTC, zarathustra323 requested changes

2022-04-28 21:15 UTC, zarathustra323 commented on services/graphql/src/graphql/definitions/field.js
> +  canWriteIn: Boolean!
Allow this to be nullable

2022-04-28 21:15 UTC, zarathustra323 commented on services/graphql/src/graphql/definitions/app-user.js
> +  "BC support: The select option ID. Also used as the option value."
Remove the BC comments

2022-04-28 21:15 UTC, zarathustra323 commented on services/application/src/actions/user/update-custom-select-answers.js
> -    .filter(({ optionIds }) => optionIds.length) // ignore/unset fields without options
Put this back for now so that inactive answers aren't removed

2022-04-29 15:28 UTC, zarathustra323 approved these changes

2022-04-29 15:29 UTC, merged

2022-05-02 15:46 UTC, solocommand commented
![](https://github.trello.services/images/mini-trello-icon.png) [Support write-in values on select fields](https://trello.com/c/GB789yV5/3-support-write-in-values-on-select-fields)