Allow for alternative verbiages for login link email
parameter1/identity-x pull request #29
Opened 2023-02-08 21:58 UTC by Shinsina

2023-02-08 21:59 UTC, Shinsina commented
![](https://github.trello.services/images/mini-trello-icon.png) [Translate Newsletter Sign-up Confirmation verbiage](https://trello.com/c/mTiOcAqU/493-translate-newsletter-sign-up-confirmation-verbiage)

2023-04-11 15:03 UTC, solocommand requested changes
@Shinsina a few changes here. First off, the indentation shouldn't be changed for the plain text, as this will be treated literally and indented weird when delivered.

Rather than hardcoding an ID, add a language selector to the app settings screen https://identity-x.parameter1.com/orgs/5e28a144f7614f1d488bd70e/apps/edit/5e28a4c858e67b86c955ae4d. Default the setting to `en-us` in the application model's schema def, and allow `es-mx` as an enum option. You should be able to swap between languages via the UI here and test login links.

Store these templates as different files (such as `./templates/en-us.js`). Pass the required variables through to them and return the text/html/subject. Something like this:
```js
module.exports = ({
  sendingDomain,
  supportEmail,
  url,
  appName,
  addressValues,
} = {}) => {
  html: `...template`,
  text: `...template`,
  subject: `...template`,
};
```

2023-04-13 16:04 UTC, solocommand requested changes
Looks good, one cleanup change to make. 

I'm also not sure that this _should_ throw an error if there is no language template...IMO it should fall back to the `en-us` template as the default since this would break the entire login functionality for end users.

2023-04-13 16:04 UTC, solocommand commented on services/application/src/actions/user/send-login-link.js
Lets clean this part up a bit -- create an `email-templates/login-link/index.js` file that imports and exports the language functions.

Then this whole section can be condensed to something like this:
```js
if (!template[language]) throw createError(404, ...);
const { subject, html, text } = template[language]({ sendingDomain, ... });
```

2023-04-13 18:18 UTC, solocommand approved these changes

2023-04-13 18:18 UTC, merged