Add AppUser phone number
parameter1/identity-x pull request #9
Opened 2022-02-22 23:18 UTC by solocommand

![image](https://user-images.githubusercontent.com/1778222/155235980-191092cc-2d74-4219-9da3-5cc7d5ffdd08.png)

2022-02-22 23:23 UTC, solocommand commented
![](https://github.trello.services/images/mini-trello-icon.png) [Fields on Identity X to set to required](https://trello.com/c/dM6HfndK/257-fields-on-identity-x-to-set-to-required)

2022-03-09 21:27 UTC, zarathustra323 requested changes

2022-03-09 21:27 UTC, zarathustra323 commented on services/manage/app/templates/components/app-user/modal-form/general-fields.hbs
> +      <Input @id="app-user.phone-number" @type="text" @class="form-control" @value={{this.model.phoneNumber}} />
Change to type `tel`

2022-03-09 22:01 UTC, zarathustra323 approved these changes

2022-03-09 22:01 UTC, merged